// AUTOGENERATED with quazal-tools

#![allow(clippy::enum_variant_names, clippy::upper_case_acronyms)]
#[derive(Debug, ToStream, FromStream)]
pub struct UbiAuthenticationLoginCustomData {
    pub data: quazal::rmc::types::Data,
    pub user_name: String,
    pub online_key: String,
    pub password: String,
}
