// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const CHALLENGE_HELPER_PROTOCOL_ID: u16 = 105u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum ChallengeHelperProtocolMethod {
    GenerateMyFriendChallenges = 1u32,
    GenerateFriendChallenges = 2u32,
    GetOnlineChallenges = 3u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GenerateMyFriendChallengesRequest {
    pub friend_pids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GenerateMyFriendChallengesResponse {
    pub result: quazal::rmc::types::QList<FriendChallenge>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GenerateFriendChallengesRequest {
    pub target_pid: u32,
    pub friend_pids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GenerateFriendChallengesResponse {
    pub result: quazal::rmc::types::QList<FriendChallenge>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetOnlineChallengesRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct GetOnlineChallengesResponse {
    pub online_challenges: quazal::rmc::types::QList<OnlineChallenge>,
}
pub struct ChallengeHelperProtocolServer<T: ChallengeHelperProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: ChallengeHelperProtocolServerTrait<CI>, CI> ChallengeHelperProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: ChallengeHelperProtocolServerTrait<CI>, CI> Protocol<CI> for ChallengeHelperProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        CHALLENGE_HELPER_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "ChallengeHelperProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        3u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = ChallengeHelperProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(ChallengeHelperProtocolMethod::GenerateMyFriendChallenges) => {
                let req = GenerateMyFriendChallengesRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .generate_my_friend_challenges(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(ChallengeHelperProtocolMethod::GenerateFriendChallenges) => {
                let req = GenerateFriendChallengesRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .generate_friend_challenges(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(ChallengeHelperProtocolMethod::GetOnlineChallenges) => {
                let req = GetOnlineChallengesRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_online_challenges(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        ChallengeHelperProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait ChallengeHelperProtocolServerTrait<CI> {
    fn generate_my_friend_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GenerateMyFriendChallengesRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GenerateMyFriendChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(generate_my_friend_challenges)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn generate_friend_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GenerateFriendChallengesRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GenerateFriendChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(generate_friend_challenges)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_online_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetOnlineChallengesRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetOnlineChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(get_online_challenges)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct ChallengeHelperProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> ChallengeHelperProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for ChallengeHelperProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for ChallengeHelperProtocolClient<CI> {
    fn id(&self) -> u16 {
        CHALLENGE_HELPER_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "ChallengeHelperProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        3u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        ChallengeHelperProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> ChallengeHelperProtocolClient<CI> {
    pub fn generate_my_friend_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GenerateMyFriendChallengesRequest,
    ) -> Result<GenerateMyFriendChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(generate_my_friend_challenges)
        );
        self.send(
            logger,
            ctx,
            ci,
            ChallengeHelperProtocolMethod::GenerateMyFriendChallenges as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn generate_friend_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GenerateFriendChallengesRequest,
    ) -> Result<GenerateFriendChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(generate_friend_challenges)
        );
        self.send(
            logger,
            ctx,
            ci,
            ChallengeHelperProtocolMethod::GenerateFriendChallenges as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_online_challenges(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetOnlineChallengesRequest,
    ) -> Result<GetOnlineChallengesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "ChallengeHelperProtocol",
            stringify!(get_online_challenges)
        );
        self.send(
            logger,
            ctx,
            ci,
            ChallengeHelperProtocolMethod::GetOnlineChallenges as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
