// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

use super::types::*;
pub const UPLAY_WIN_PROTOCOL_ID: u16 = 49u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum UplayWinProtocolMethod {
    GetActions = 1u32,
    GetActionsCompleted = 2u32,
    GetActionsCount = 3u32,
    GetActionsCompletedCount = 4u32,
    GetRewards = 5u32,
    GetRewardsPurchased = 6u32,
    UplayWelcome = 7u32,
    SetActionCompleted = 8u32,
    SetActionsCompleted = 9u32,
    GetUserToken = 10u32,
    GetVirtualCurrencyUserBalance = 11u32,
    GetSectionsByKey = 12u32,
    BuyReward = 13u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsRequest {
    pub start_row_index: i32,
    pub maximum_rows: i32,
    pub sort_expression: String,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsResponse {
    pub action_list: quazal::rmc::types::QList<UplayAction>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCompletedRequest {
    pub start_row_index: i32,
    pub maximum_rows: i32,
    pub sort_expression: String,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCompletedResponse {
    pub action_list: quazal::rmc::types::QList<UplayAction>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCountRequest {
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCountResponse {
    pub actions_count: i32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCompletedCountRequest {
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetActionsCompletedCountResponse {
    pub actions_count: i32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetRewardsRequest {
    pub start_row_index: i32,
    pub maximum_rows: i32,
    pub sort_expression: String,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetRewardsResponse {
    pub reward_list: quazal::rmc::types::QList<UplayReward>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetRewardsPurchasedRequest {
    pub start_row_index: i32,
    pub maximum_rows: i32,
    pub sort_expression: String,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetRewardsPurchasedResponse {
    pub reward_list: quazal::rmc::types::QList<UplayReward>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UplayWelcomeRequest {
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UplayWelcomeResponse {
    pub action_list: quazal::rmc::types::QList<UplayAction>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetActionCompletedRequest {
    pub action_code: String,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetActionCompletedResponse {
    pub unlocked_action: UplayAction,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetActionsCompletedRequest {
    pub action_code_list: quazal::rmc::types::QList<String>,
    pub culture_name: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetActionsCompletedResponse {
    pub action_list: quazal::rmc::types::QList<UplayAction>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetUserTokenRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct GetUserTokenResponse {
    pub token: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetVirtualCurrencyUserBalanceRequest {
    pub platform_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetVirtualCurrencyUserBalanceResponse {
    pub virtual_currency_user_balance: i32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetSectionsByKeyRequest {
    pub culture_name: String,
    pub section_key: String,
    pub platform_code: String,
    pub game_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetSectionsByKeyResponse {
    pub section_list: quazal::rmc::types::QList<UplaySection>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct BuyRewardRequest {
    pub reward_code: String,
    pub platform_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct BuyRewardResponse {
    pub virtual_currency_user_balance: i32,
}
pub struct UplayWinProtocolServer<T: UplayWinProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: UplayWinProtocolServerTrait<CI>, CI> UplayWinProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: UplayWinProtocolServerTrait<CI>, CI> Protocol<CI> for UplayWinProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        UPLAY_WIN_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "UplayWinProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        13u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = UplayWinProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(UplayWinProtocolMethod::GetActions) => {
                let req = GetActionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_actions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetActionsCompleted) => {
                let req = GetActionsCompletedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .get_actions_completed(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetActionsCount) => {
                let req = GetActionsCountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_actions_count(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetActionsCompletedCount) => {
                let req = GetActionsCompletedCountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_actions_completed_count(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetRewards) => {
                let req = GetRewardsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_rewards(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetRewardsPurchased) => {
                let req = GetRewardsPurchasedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .get_rewards_purchased(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::UplayWelcome) => {
                let req = UplayWelcomeRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .uplay_welcome(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::SetActionCompleted) => {
                let req = SetActionCompletedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .set_action_completed(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::SetActionsCompleted) => {
                let req = SetActionsCompletedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .set_actions_completed(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetUserToken) => {
                let req = GetUserTokenRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_user_token(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetVirtualCurrencyUserBalance) => {
                let req = GetVirtualCurrencyUserBalanceRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_virtual_currency_user_balance(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::GetSectionsByKey) => {
                let req = GetSectionsByKeyRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .get_sections_by_key(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UplayWinProtocolMethod::BuyReward) => {
                let req = BuyRewardRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .buy_reward(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        UplayWinProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait UplayWinProtocolServerTrait<CI> {
    fn get_actions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetActionsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_actions_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCompletedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetActionsCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_completed)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_actions_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetActionsCountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_count)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_actions_completed_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCompletedCountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetActionsCompletedCountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_completed_count)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_rewards(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetRewardsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetRewardsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_rewards)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_rewards_purchased(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetRewardsPurchasedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetRewardsPurchasedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_rewards_purchased)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn uplay_welcome(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UplayWelcomeRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<UplayWelcomeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(uplay_welcome)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn set_action_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetActionCompletedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SetActionCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(set_action_completed)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn set_actions_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetActionsCompletedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SetActionsCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(set_actions_completed)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_user_token(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetUserTokenRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetUserTokenResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_user_token)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_virtual_currency_user_balance(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetVirtualCurrencyUserBalanceRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetVirtualCurrencyUserBalanceResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_virtual_currency_user_balance)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_sections_by_key(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetSectionsByKeyRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetSectionsByKeyResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_sections_by_key)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn buy_reward(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: BuyRewardRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<BuyRewardResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(buy_reward)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct UplayWinProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> UplayWinProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> ClientProtocol<CI> for UplayWinProtocolClient<CI> {
    fn id(&self) -> u16 {
        UPLAY_WIN_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "UplayWinProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        13u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        UplayWinProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> UplayWinProtocolClient<CI> {
    pub fn get_actions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsRequest,
    ) -> Result<GetActionsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetActions as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_actions_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCompletedRequest,
    ) -> Result<GetActionsCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_completed)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetActionsCompleted as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_actions_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCountRequest,
    ) -> Result<GetActionsCountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_count)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetActionsCount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_actions_completed_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetActionsCompletedCountRequest,
    ) -> Result<GetActionsCompletedCountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_actions_completed_count)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetActionsCompletedCount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_rewards(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetRewardsRequest,
    ) -> Result<GetRewardsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_rewards)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetRewards as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_rewards_purchased(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetRewardsPurchasedRequest,
    ) -> Result<GetRewardsPurchasedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_rewards_purchased)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetRewardsPurchased as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn uplay_welcome(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UplayWelcomeRequest,
    ) -> Result<UplayWelcomeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(uplay_welcome)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::UplayWelcome as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn set_action_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetActionCompletedRequest,
    ) -> Result<SetActionCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(set_action_completed)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::SetActionCompleted as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn set_actions_completed(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetActionsCompletedRequest,
    ) -> Result<SetActionsCompletedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(set_actions_completed)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::SetActionsCompleted as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_user_token(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetUserTokenRequest,
    ) -> Result<GetUserTokenResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_user_token)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetUserToken as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_virtual_currency_user_balance(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetVirtualCurrencyUserBalanceRequest,
    ) -> Result<GetVirtualCurrencyUserBalanceResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_virtual_currency_user_balance)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetVirtualCurrencyUserBalance as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_sections_by_key(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetSectionsByKeyRequest,
    ) -> Result<GetSectionsByKeyResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(get_sections_by_key)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::GetSectionsByKey as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn buy_reward(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: BuyRewardRequest,
    ) -> Result<BuyRewardResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UplayWinProtocol",
            stringify!(buy_reward)
        );
        self.send(
            logger,
            ctx,
            ci,
            UplayWinProtocolMethod::BuyReward as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
