// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

use super::types::*;
pub const PLAYER_STATS_PROTOCOL_ID: u16 = 55u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum PlayerStatsProtocolMethod {
    WriteStats = 1u32,
    ReadStatsByPlayers = 2u32,
    ReadLeaderboardsNearPlayer = 3u32,
    ReadLeaderboardsByRank = 4u32,
    ReadLeaderboardsByPlayers = 5u32,
    ReadStatboardHistory = 6u32,
    ReadLeaderboardHistory = 7u32,
    ReadStatboardHistoryAggregated = 8u32,
    GetStatboardNextPurgeDate = 9u32,
    ReadLeaderboardsNearPlayer2 = 10u32,
    ReadLeaderboardsByRank2 = 11u32,
    ReadLeaderboardsByPlayers2 = 12u32,
    ReadPopulationStats = 13u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct WriteStatsRequest {
    pub player_stat_updates: quazal::rmc::types::QList<PlayerStatUpdate>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct WriteStatsResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatsByPlayersRequest {
    pub player_pids: quazal::rmc::types::QList<u32>,
    pub queries: quazal::rmc::types::QList<StatboardQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatsByPlayersResponse {
    pub results: quazal::rmc::types::QList<StatboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsNearPlayerRequest {
    pub player_pid: u32,
    pub count: u32,
    pub queries: quazal::rmc::types::QList<LeaderboardQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsNearPlayerResponse {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByRankRequest {
    pub starting_rank: u32,
    pub count: u32,
    pub queries: quazal::rmc::types::QList<LeaderboardQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByRankResponse {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByPlayersRequest {
    pub player_pids: quazal::rmc::types::QList<u32>,
    pub queries: quazal::rmc::types::QList<LeaderboardQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByPlayersResponse {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatboardHistoryRequest {
    pub queries: quazal::rmc::types::QList<StatboardHistoryQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatboardHistoryResponse {
    pub results: quazal::rmc::types::QList<StatboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardHistoryRequest {
    pub queries: quazal::rmc::types::QList<LeaderboardHistoryQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardHistoryResponse {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatboardHistoryAggregatedRequest {
    pub queries: quazal::rmc::types::QList<StatboardHistoryAggregatedQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadStatboardHistoryAggregatedResponse {
    pub results: quazal::rmc::types::QList<StatboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetStatboardNextPurgeDateRequest {
    pub board_id: u32,
    pub reset_frequency: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetStatboardNextPurgeDateResponse {
    pub purge_date: quazal::rmc::types::DateTime,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsNearPlayer2Request {
    pub player_pid: u32,
    pub count: u32,
    pub queries: quazal::rmc::types::QList<LeaderboardQuery2>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsNearPlayer2Response {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByRank2Request {
    pub starting_rank: u32,
    pub count: u32,
    pub queries: quazal::rmc::types::QList<LeaderboardQuery2>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByRank2Response {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByPlayers2Request {
    pub queries: quazal::rmc::types::QList<LeaderboardQuery2>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadLeaderboardsByPlayers2Response {
    pub results: quazal::rmc::types::QList<LeaderboardResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadPopulationStatsRequest {
    pub queries: quazal::rmc::types::QList<PopulationStatQuery>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReadPopulationStatsResponse {
    pub results: quazal::rmc::types::QList<PopulationStatResult>,
}
pub struct PlayerStatsProtocolServer<T: PlayerStatsProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: PlayerStatsProtocolServerTrait<CI>, CI> PlayerStatsProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: PlayerStatsProtocolServerTrait<CI>, CI> Protocol<CI> for PlayerStatsProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        PLAYER_STATS_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "PlayerStatsProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        13u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = PlayerStatsProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(PlayerStatsProtocolMethod::WriteStats) => {
                let req = WriteStatsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .write_stats(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadStatsByPlayers) => {
                let req = ReadStatsByPlayersRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .read_stats_by_players(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsNearPlayer) => {
                let req = ReadLeaderboardsNearPlayerRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_leaderboards_near_player(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsByRank) => {
                let req = ReadLeaderboardsByRankRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .read_leaderboards_by_rank(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsByPlayers) => {
                let req = ReadLeaderboardsByPlayersRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_leaderboards_by_players(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadStatboardHistory) => {
                let req = ReadStatboardHistoryRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .read_statboard_history(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardHistory) => {
                let req = ReadLeaderboardHistoryRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .read_leaderboard_history(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadStatboardHistoryAggregated) => {
                let req = ReadStatboardHistoryAggregatedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_statboard_history_aggregated(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::GetStatboardNextPurgeDate) => {
                let req = GetStatboardNextPurgeDateRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_statboard_next_purge_date(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsNearPlayer2) => {
                let req = ReadLeaderboardsNearPlayer2Request::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_leaderboards_near_player_2(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsByRank2) => {
                let req = ReadLeaderboardsByRank2Request::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_leaderboards_by_rank_2(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadLeaderboardsByPlayers2) => {
                let req = ReadLeaderboardsByPlayers2Request::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.read_leaderboards_by_players_2(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(PlayerStatsProtocolMethod::ReadPopulationStats) => {
                let req = ReadPopulationStatsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .read_population_stats(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        PlayerStatsProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait PlayerStatsProtocolServerTrait<CI> {
    fn write_stats(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: WriteStatsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<WriteStatsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(write_stats)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_stats_by_players(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatsByPlayersRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadStatsByPlayersResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_stats_by_players)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_near_player(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsNearPlayerRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsNearPlayerResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_near_player)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_by_rank(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByRankRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsByRankResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_rank)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_by_players(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByPlayersRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsByPlayersResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_players)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_statboard_history(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatboardHistoryRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadStatboardHistoryResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_statboard_history)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboard_history(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardHistoryRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardHistoryResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboard_history)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_statboard_history_aggregated(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatboardHistoryAggregatedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadStatboardHistoryAggregatedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_statboard_history_aggregated)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_statboard_next_purge_date(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetStatboardNextPurgeDateRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetStatboardNextPurgeDateResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(get_statboard_next_purge_date)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_near_player_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsNearPlayer2Request,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsNearPlayer2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_near_player_2)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_by_rank_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByRank2Request,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsByRank2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_rank_2)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_leaderboards_by_players_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByPlayers2Request,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadLeaderboardsByPlayers2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_players_2)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn read_population_stats(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadPopulationStatsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReadPopulationStatsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_population_stats)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct PlayerStatsProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> PlayerStatsProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> ClientProtocol<CI> for PlayerStatsProtocolClient<CI> {
    fn id(&self) -> u16 {
        PLAYER_STATS_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "PlayerStatsProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        13u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        PlayerStatsProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> PlayerStatsProtocolClient<CI> {
    pub fn write_stats(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: WriteStatsRequest,
    ) -> Result<WriteStatsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(write_stats)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::WriteStats as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_stats_by_players(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatsByPlayersRequest,
    ) -> Result<ReadStatsByPlayersResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_stats_by_players)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadStatsByPlayers as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_near_player(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsNearPlayerRequest,
    ) -> Result<ReadLeaderboardsNearPlayerResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_near_player)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsNearPlayer as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_by_rank(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByRankRequest,
    ) -> Result<ReadLeaderboardsByRankResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_rank)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsByRank as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_by_players(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByPlayersRequest,
    ) -> Result<ReadLeaderboardsByPlayersResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_players)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsByPlayers as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_statboard_history(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatboardHistoryRequest,
    ) -> Result<ReadStatboardHistoryResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_statboard_history)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadStatboardHistory as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboard_history(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardHistoryRequest,
    ) -> Result<ReadLeaderboardHistoryResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboard_history)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardHistory as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_statboard_history_aggregated(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadStatboardHistoryAggregatedRequest,
    ) -> Result<ReadStatboardHistoryAggregatedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_statboard_history_aggregated)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadStatboardHistoryAggregated as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_statboard_next_purge_date(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetStatboardNextPurgeDateRequest,
    ) -> Result<GetStatboardNextPurgeDateResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(get_statboard_next_purge_date)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::GetStatboardNextPurgeDate as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_near_player_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsNearPlayer2Request,
    ) -> Result<ReadLeaderboardsNearPlayer2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_near_player_2)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsNearPlayer2 as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_by_rank_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByRank2Request,
    ) -> Result<ReadLeaderboardsByRank2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_rank_2)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsByRank2 as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_leaderboards_by_players_2(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadLeaderboardsByPlayers2Request,
    ) -> Result<ReadLeaderboardsByPlayers2Response, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_leaderboards_by_players_2)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadLeaderboardsByPlayers2 as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn read_population_stats(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReadPopulationStatsRequest,
    ) -> Result<ReadPopulationStatsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "PlayerStatsProtocol",
            stringify!(read_population_stats)
        );
        self.send(
            logger,
            ctx,
            ci,
            PlayerStatsProtocolMethod::ReadPopulationStats as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
