// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const GAME_SESSION_PROTOCOL_ID: u16 = 42u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum GameSessionProtocolMethod {
    CreateSession = 1u32,
    UpdateSession = 2u32,
    DeleteSession = 3u32,
    MigrateSession = 4u32,
    LeaveSession = 5u32,
    GetSession = 6u32,
    SearchSessions = 7u32,
    AddParticipants = 8u32,
    RemoveParticipants = 9u32,
    GetParticipantCount = 10u32,
    GetParticipants = 11u32,
    SendInvitation = 12u32,
    GetInvitationReceivedCount = 13u32,
    GetInvitationsReceived = 14u32,
    GetInvitationSentCount = 15u32,
    GetInvitationsSent = 16u32,
    AcceptInvitation = 17u32,
    DeclineInvitation = 18u32,
    CancelInvitation = 19u32,
    SendTextMessage = 20u32,
    RegisterUrLs = 21u32,
    JoinSession = 22u32,
    AbandonSession = 23u32,
    SearchSessionsWithParticipants = 24u32,
    GetSessions = 25u32,
    GetParticipantsUrLs = 26u32,
    MigrateSessionHost = 27u32,
    SplitSession = 28u32,
    SearchSocialSessions = 29u32,
    ReportUnsuccessfulJoinSessions = 30u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct CreateSessionRequest {
    pub game_session: GameSession,
}
#[derive(Debug, ToStream, FromStream)]
pub struct CreateSessionResponse {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UpdateSessionRequest {
    pub game_session_update: GameSessionUpdate,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UpdateSessionResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct DeleteSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct DeleteSessionResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct MigrateSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct MigrateSessionResponse {
    pub game_session_key_migrated: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LeaveSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LeaveSessionResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct GetSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetSessionResponse {
    pub search_result: GameSessionSearchResult,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsRequest {
    pub game_session_query: GameSessionQuery,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsResponse {
    pub search_results: quazal::rmc::types::QList<GameSessionSearchResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AddParticipantsRequest {
    pub game_session_key: GameSessionKey,
    pub public_participant_ids: quazal::rmc::types::QList<u32>,
    pub private_participant_ids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AddParticipantsResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct RemoveParticipantsRequest {
    pub game_session_key: GameSessionKey,
    pub participant_ids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct RemoveParticipantsResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantCountRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantCountResponse {
    pub count: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantsRequest {
    pub game_session_key: GameSessionKey,
    pub result_range: quazal::rmc::types::ResultRange,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantsResponse {
    pub participants: quazal::rmc::types::QList<GameSessionParticipant>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendInvitationRequest {
    pub invitation: GameSessionInvitation,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendInvitationResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationReceivedCountRequest {
    pub game_session_type_id: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationReceivedCountResponse {
    pub count: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationsReceivedRequest {
    pub game_session_type_id: u32,
    pub result_range: quazal::rmc::types::ResultRange,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationsReceivedResponse {
    pub invitations: quazal::rmc::types::QList<GameSessionInvitationReceived>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationSentCountRequest {
    pub game_session_type_id: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationSentCountResponse {
    pub count: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationsSentRequest {
    pub game_session_type_id: u32,
    pub result_range: quazal::rmc::types::ResultRange,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetInvitationsSentResponse {
    pub invitations: quazal::rmc::types::QList<GameSessionInvitationSent>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AcceptInvitationRequest {
    pub game_session_invitation: GameSessionInvitationReceived,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AcceptInvitationResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct DeclineInvitationRequest {
    pub game_session_invitation: GameSessionInvitationReceived,
}
#[derive(Debug, ToStream, FromStream)]
pub struct DeclineInvitationResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct CancelInvitationRequest {
    pub game_session_invitation: GameSessionInvitationSent,
}
#[derive(Debug, ToStream, FromStream)]
pub struct CancelInvitationResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct SendTextMessageRequest {
    pub game_session_message: GameSessionMessage,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTextMessageResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct RegisterUrLsRequest {
    pub station_urls: quazal::rmc::types::QList<quazal::rmc::types::StationURL>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct RegisterUrLsResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct JoinSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct JoinSessionResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct AbandonSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AbandonSessionResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsWithParticipantsRequest {
    pub game_session_type_id: u32,
    pub participant_ids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsWithParticipantsResponse {
    pub search_results: quazal::rmc::types::QList<GameSessionSearchWithParticipantsResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetSessionsRequest {
    pub game_session_keys: quazal::rmc::types::QList<GameSessionKey>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetSessionsResponse {
    pub search_results: quazal::rmc::types::QList<GameSessionSearchResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantsUrLsRequest {
    pub game_session_key: GameSessionKey,
    pub participant_ids: quazal::rmc::types::QList<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetParticipantsUrLsResponse {
    pub participants: quazal::rmc::types::QList<GameSessionParticipant>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct MigrateSessionHostRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct MigrateSessionHostResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct SplitSessionRequest {
    pub game_session_key: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SplitSessionResponse {
    pub game_session_key_migrated: GameSessionKey,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSocialSessionsRequest {
    pub game_session_social_query: GameSessionSocialQuery,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSocialSessionsResponse {
    pub search_results: quazal::rmc::types::QList<GameSessionSearchWithParticipantsResult>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReportUnsuccessfulJoinSessionsRequest {
    pub unsuccessful_join_sessions: quazal::rmc::types::QList<GameSessionUnsuccessfulJoinSession>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ReportUnsuccessfulJoinSessionsResponse;
pub struct GameSessionProtocolServer<T: GameSessionProtocolServerTrait<CI>, CI>(T, ::std::marker::PhantomData<CI>);
impl<T: GameSessionProtocolServerTrait<CI>, CI> GameSessionProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: GameSessionProtocolServerTrait<CI>, CI> Protocol<CI> for GameSessionProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        GAME_SESSION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "GameSessionProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        30u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = GameSessionProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(GameSessionProtocolMethod::CreateSession) => {
                let req = CreateSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.create_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::UpdateSession) => {
                let req = UpdateSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.update_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::DeleteSession) => {
                let req = DeleteSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.delete_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::MigrateSession) => {
                let req = MigrateSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.migrate_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::LeaveSession) => {
                let req = LeaveSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.leave_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetSession) => {
                let req = GetSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SearchSessions) => {
                let req = SearchSessionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.search_sessions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::AddParticipants) => {
                let req = AddParticipantsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.add_participants(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::RemoveParticipants) => {
                let req = RemoveParticipantsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.remove_participants(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetParticipantCount) => {
                let req = GetParticipantCountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_participant_count(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetParticipants) => {
                let req = GetParticipantsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_participants(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SendInvitation) => {
                let req = SendInvitationRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_invitation(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetInvitationReceivedCount) => {
                let req = GetInvitationReceivedCountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_invitation_received_count(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetInvitationsReceived) => {
                let req = GetInvitationsReceivedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_invitations_received(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetInvitationSentCount) => {
                let req = GetInvitationSentCountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_invitation_sent_count(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetInvitationsSent) => {
                let req = GetInvitationsSentRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_invitations_sent(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::AcceptInvitation) => {
                let req = AcceptInvitationRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.accept_invitation(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::DeclineInvitation) => {
                let req = DeclineInvitationRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.decline_invitation(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::CancelInvitation) => {
                let req = CancelInvitationRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.cancel_invitation(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SendTextMessage) => {
                let req = SendTextMessageRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_text_message(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::RegisterUrLs) => {
                let req = RegisterUrLsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.register_urls(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::JoinSession) => {
                let req = JoinSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.join_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::AbandonSession) => {
                let req = AbandonSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.abandon_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SearchSessionsWithParticipants) => {
                let req = SearchSessionsWithParticipantsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.search_sessions_with_participants(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetSessions) => {
                let req = GetSessionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_sessions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::GetParticipantsUrLs) => {
                let req = GetParticipantsUrLsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_participants_urls(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::MigrateSessionHost) => {
                let req = MigrateSessionHostRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.migrate_session_host(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SplitSession) => {
                let req = SplitSessionRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.split_session(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::SearchSocialSessions) => {
                let req = SearchSocialSessionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.search_social_sessions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(GameSessionProtocolMethod::ReportUnsuccessfulJoinSessions) => {
                let req = ReportUnsuccessfulJoinSessionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.report_unsuccessful_join_sessions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        GameSessionProtocolMethod::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait GameSessionProtocolServerTrait<CI> {
    fn create_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: CreateSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<CreateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(create_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn update_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UpdateSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<UpdateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(update_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn delete_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: DeleteSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<DeleteSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(delete_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn migrate_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: MigrateSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<MigrateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(migrate_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn leave_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LeaveSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LeaveSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(leave_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn search_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSessionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SearchSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_sessions));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn add_participants(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: AddParticipantsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<AddParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(add_participants));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn remove_participants(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: RemoveParticipantsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<RemoveParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(remove_participants));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_participant_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetParticipantCountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetParticipantCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participant_count));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_participants(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetParticipantsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participants));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn send_invitation(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendInvitationRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(send_invitation));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_invitation_received_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationReceivedCountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetInvitationReceivedCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitation_received_count));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_invitations_received(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationsReceivedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetInvitationsReceivedResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitations_received));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_invitation_sent_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationSentCountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetInvitationSentCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitation_sent_count));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_invitations_sent(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationsSentRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetInvitationsSentResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitations_sent));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn accept_invitation(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: AcceptInvitationRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<AcceptInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(accept_invitation));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn decline_invitation(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: DeclineInvitationRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<DeclineInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(decline_invitation));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn cancel_invitation(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: CancelInvitationRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<CancelInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(cancel_invitation));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn send_text_message(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendTextMessageRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendTextMessageResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(send_text_message));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn register_urls(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: RegisterUrLsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<RegisterUrLsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(register_urls));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn join_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: JoinSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<JoinSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(join_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn abandon_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: AbandonSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<AbandonSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(abandon_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn search_sessions_with_participants(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSessionsWithParticipantsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SearchSessionsWithParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_sessions_with_participants));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetSessionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_sessions));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_participants_urls(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetParticipantsUrLsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetParticipantsUrLsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participants_urls));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn migrate_session_host(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: MigrateSessionHostRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<MigrateSessionHostResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(migrate_session_host));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn split_session(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SplitSessionRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SplitSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(split_session));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn search_social_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSocialSessionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SearchSocialSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_social_sessions));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn report_unsuccessful_join_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReportUnsuccessfulJoinSessionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ReportUnsuccessfulJoinSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(report_unsuccessful_join_sessions));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct GameSessionProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> GameSessionProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for GameSessionProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for GameSessionProtocolClient<CI> {
    fn id(&self) -> u16 {
        GAME_SESSION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "GameSessionProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        30u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        GameSessionProtocolMethod::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> GameSessionProtocolClient<CI> {
    pub fn create_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: CreateSessionRequest) -> Result<CreateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(create_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::CreateSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn update_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: UpdateSessionRequest) -> Result<UpdateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(update_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::UpdateSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn delete_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: DeleteSessionRequest) -> Result<DeleteSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(delete_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::DeleteSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn migrate_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: MigrateSessionRequest) -> Result<MigrateSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(migrate_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::MigrateSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn leave_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: LeaveSessionRequest) -> Result<LeaveSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(leave_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::LeaveSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: GetSessionRequest) -> Result<GetSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn search_sessions(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SearchSessionsRequest) -> Result<SearchSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_sessions));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SearchSessions as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn add_participants(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: AddParticipantsRequest) -> Result<AddParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(add_participants));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::AddParticipants as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn remove_participants(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: RemoveParticipantsRequest) -> Result<RemoveParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(remove_participants));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::RemoveParticipants as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_participant_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetParticipantCountRequest,
    ) -> Result<GetParticipantCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participant_count));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetParticipantCount as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_participants(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: GetParticipantsRequest) -> Result<GetParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participants));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetParticipants as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn send_invitation(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SendInvitationRequest) -> Result<SendInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(send_invitation));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SendInvitation as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_invitation_received_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationReceivedCountRequest,
    ) -> Result<GetInvitationReceivedCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitation_received_count));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetInvitationReceivedCount as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_invitations_received(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationsReceivedRequest,
    ) -> Result<GetInvitationsReceivedResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitations_received));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetInvitationsReceived as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_invitation_sent_count(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetInvitationSentCountRequest,
    ) -> Result<GetInvitationSentCountResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitation_sent_count));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetInvitationSentCount as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_invitations_sent(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: GetInvitationsSentRequest) -> Result<GetInvitationsSentResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_invitations_sent));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetInvitationsSent as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn accept_invitation(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: AcceptInvitationRequest) -> Result<AcceptInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(accept_invitation));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::AcceptInvitation as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn decline_invitation(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: DeclineInvitationRequest) -> Result<DeclineInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(decline_invitation));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::DeclineInvitation as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn cancel_invitation(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: CancelInvitationRequest) -> Result<CancelInvitationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(cancel_invitation));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::CancelInvitation as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn send_text_message(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SendTextMessageRequest) -> Result<SendTextMessageResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(send_text_message));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SendTextMessage as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn register_urls(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: RegisterUrLsRequest) -> Result<RegisterUrLsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(register_urls));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::RegisterUrLs as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn join_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: JoinSessionRequest) -> Result<JoinSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(join_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::JoinSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn abandon_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: AbandonSessionRequest) -> Result<AbandonSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(abandon_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::AbandonSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn search_sessions_with_participants(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSessionsWithParticipantsRequest,
    ) -> Result<SearchSessionsWithParticipantsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_sessions_with_participants));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SearchSessionsWithParticipants as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_sessions(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: GetSessionsRequest) -> Result<GetSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_sessions));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetSessions as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_participants_urls(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetParticipantsUrLsRequest,
    ) -> Result<GetParticipantsUrLsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(get_participants_urls));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::GetParticipantsUrLs as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn migrate_session_host(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: MigrateSessionHostRequest) -> Result<MigrateSessionHostResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(migrate_session_host));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::MigrateSessionHost as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn split_session(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SplitSessionRequest) -> Result<SplitSessionResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(split_session));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SplitSession as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn search_social_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSocialSessionsRequest,
    ) -> Result<SearchSocialSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(search_social_sessions));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::SearchSocialSessions as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn report_unsuccessful_join_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ReportUnsuccessfulJoinSessionsRequest,
    ) -> Result<ReportUnsuccessfulJoinSessionsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "GameSessionProtocol", stringify!(report_unsuccessful_join_sessions));
        self.send(logger, ctx, ci, GameSessionProtocolMethod::ReportUnsuccessfulJoinSessions as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
