// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const TRACKING_PROTOCOL_3_ID: u16 = 36u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum TrackingProtocol3Method {
    SendTag = 1u32,
    SendTagAndUpdateUserInfo = 2u32,
    SendUserInfo = 3u32,
    GetConfiguration = 4u32,
    SendTags = 5u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagRequest {
    pub tracking_id: u32,
    pub tag: String,
    pub attributes: String,
    pub delta_time: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagAndUpdateUserInfoRequest {
    pub tracking_id: u32,
    pub tag: String,
    pub attributes: String,
    pub delta_time: u32,
    pub user_id: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagAndUpdateUserInfoResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct SendUserInfoRequest {
    pub delta_time: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendUserInfoResponse {
    pub user_info: TrackingInformation,
    pub tracking_id: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetConfigurationRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct GetConfigurationResponse {
    pub tags: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagsRequest {
    pub tag_data: Vec<TrackingTag>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SendTagsResponse;
pub struct TrackingProtocol3Server<T: TrackingProtocol3ServerTrait<CI>, CI>(T, ::std::marker::PhantomData<CI>);
impl<T: TrackingProtocol3ServerTrait<CI>, CI> TrackingProtocol3Server<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: TrackingProtocol3ServerTrait<CI>, CI> Protocol<CI> for TrackingProtocol3Server<T, CI> {
    fn id(&self) -> u16 {
        TRACKING_PROTOCOL_3_ID
    }
    fn name(&self) -> String {
        "TrackingProtocol3".to_string()
    }
    fn num_methods(&self) -> u32 {
        5u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = TrackingProtocol3Method::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(TrackingProtocol3Method::SendTag) => {
                let req = SendTagRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_tag(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(TrackingProtocol3Method::SendTagAndUpdateUserInfo) => {
                let req = SendTagAndUpdateUserInfoRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_tag_and_update_user_info(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(TrackingProtocol3Method::SendUserInfo) => {
                let req = SendUserInfoRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_user_info(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(TrackingProtocol3Method::GetConfiguration) => {
                let req = GetConfigurationRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_configuration(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(TrackingProtocol3Method::SendTags) => {
                let req = SendTagsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.send_tags(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        TrackingProtocol3Method::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait TrackingProtocol3ServerTrait<CI> {
    fn send_tag(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendTagRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendTagResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tag));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn send_tag_and_update_user_info(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendTagAndUpdateUserInfoRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendTagAndUpdateUserInfoResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tag_and_update_user_info));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn send_user_info(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendUserInfoRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendUserInfoResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_user_info));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_configuration(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetConfigurationRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetConfigurationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(get_configuration));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn send_tags(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendTagsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SendTagsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tags));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct TrackingProtocol3Client<CI>(::std::marker::PhantomData<CI>);
impl<CI> TrackingProtocol3Client<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for TrackingProtocol3Client<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for TrackingProtocol3Client<CI> {
    fn id(&self) -> u16 {
        TRACKING_PROTOCOL_3_ID
    }
    fn name(&self) -> String {
        "TrackingProtocol3".to_string()
    }
    fn num_methods(&self) -> u32 {
        5u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        TrackingProtocol3Method::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> TrackingProtocol3Client<CI> {
    pub fn send_tag(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SendTagRequest) -> Result<SendTagResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tag));
        self.send(logger, ctx, ci, TrackingProtocol3Method::SendTag as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn send_tag_and_update_user_info(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SendTagAndUpdateUserInfoRequest,
    ) -> Result<SendTagAndUpdateUserInfoResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tag_and_update_user_info));
        self.send(logger, ctx, ci, TrackingProtocol3Method::SendTagAndUpdateUserInfo as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn send_user_info(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SendUserInfoRequest) -> Result<SendUserInfoResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_user_info));
        self.send(logger, ctx, ci, TrackingProtocol3Method::SendUserInfo as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_configuration(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: GetConfigurationRequest) -> Result<GetConfigurationResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(get_configuration));
        self.send(logger, ctx, ci, TrackingProtocol3Method::GetConfiguration as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn send_tags(&self, logger: &Logger, ctx: &Context, ci: &mut ClientInfo<CI>, request: SendTagsRequest) -> Result<SendTagsResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "TrackingProtocol3", stringify!(send_tags));
        self.send(logger, ctx, ci, TrackingProtocol3Method::SendTags as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
