// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const UBI_ACCOUNT_MANAGEMENT_PROTOCOL_ID: u16 = 29u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum UbiAccountManagementProtocolMethod {
    CreateAccount = 1u32,
    UpdateAccount = 2u32,
    GetAccount = 3u32,
    LinkAccount = 4u32,
    GetTos = 5u32,
    ValidateUsername = 6u32,
    ValidatePassword = 7u32,
    ValidateEmail = 8u32,
    GetCountryList = 9u32,
    ForgetPassword = 10u32,
    LookupPrincipalIds = 11u32,
    LookupUbiAccountIDsByPids = 12u32,
    LookupUbiAccountIDsByUsernames = 13u32,
    LookupUsernamesByUbiAccountIDs = 14u32,
    LookupUbiAccountIDsByUsernameSubString = 15u32,
    UserHasPlayed = 16u32,
    IsUserPlaying = 17u32,
    LookupUbiAccountIDsByUsernamesGlobal = 18u32,
    LookupUbiAccountIDsByEmailsGlobal = 19u32,
    LookupUsernamesByUbiAccountIDsGlobal = 20u32,
    GetTosEx = 21u32,
    HasAcceptedLatestTos = 22u32,
    AcceptLatestTos = 23u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct CreateAccountRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct CreateAccountResponse {
    pub ubi_account: UbiAccount,
    pub failed_reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UpdateAccountRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct UpdateAccountResponse {
    pub ubi_account: UbiAccount,
    pub failed_reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetAccountRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct GetAccountResponse {
    pub ubi_account: UbiAccount,
    pub exists: bool,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LinkAccountRequest {
    pub ubi_account_username: String,
    pub ubi_account_password: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LinkAccountResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct GetTosRequest {
    pub country_code: String,
    pub language_code: String,
    pub html_version: bool,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTosResponse {
    pub tos: TOS,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidateUsernameRequest {
    pub username: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidateUsernameResponse {
    pub username_validation: UsernameValidation,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidatePasswordRequest {
    pub password: String,
    pub username: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidatePasswordResponse {
    pub failed_reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidateEmailRequest {
    pub email: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidateEmailResponse {
    pub failed_reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetCountryListRequest {
    pub language_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetCountryListResponse {
    pub countries: Vec<Country>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ForgetPasswordRequest {
    pub username_or_email: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ForgetPasswordResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct LookupPrincipalIdsRequest {
    pub ubi_account_ids: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupPrincipalIdsResponse {
    pub pids: std::collections::HashMap<String, u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByPidsRequest {
    pub pids: Vec<u32>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByPidsResponse {
    pub ubiaccount_ids: std::collections::HashMap<u32, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernamesRequest {
    pub usernames: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernamesResponse {
    pub ubi_account_ids: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUsernamesByUbiAccountIDsRequest {
    pub ubi_account_ids: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUsernamesByUbiAccountIDsResponse {
    pub usernames: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernameSubStringRequest {
    pub username_sub_string: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernameSubStringResponse {
    pub ubi_account_ids: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UserHasPlayedRequest {
    pub ubi_account_ids: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UserHasPlayedResponse {
    pub user_presence: std::collections::HashMap<String, bool>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct IsUserPlayingRequest {
    pub ubi_account_ids: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct IsUserPlayingResponse {
    pub user_presence: std::collections::HashMap<String, bool>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernamesGlobalRequest {
    pub usernames: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByUsernamesGlobalResponse {
    pub ubi_account_ids: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByEmailsGlobalRequest {
    pub emails: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUbiAccountIDsByEmailsGlobalResponse {
    pub ubi_account_ids: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUsernamesByUbiAccountIDsGlobalRequest {
    pub ubi_account_ids: Vec<String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct LookupUsernamesByUbiAccountIDsGlobalResponse {
    pub usernames: std::collections::HashMap<String, String>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTosExRequest {
    pub country_code: String,
    pub language_code: String,
    pub html_version: bool,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTosExResponse {
    pub tosex: TOSEx,
}
#[derive(Debug, ToStream, FromStream)]
pub struct HasAcceptedLatestTosRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct HasAcceptedLatestTosResponse {
    pub has_accepted: bool,
    pub failed_reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct AcceptLatestTosRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct AcceptLatestTosResponse {
    pub failed_reasons: Vec<ValidationFailureReason>,
}
pub struct UbiAccountManagementProtocolServer<T: UbiAccountManagementProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: UbiAccountManagementProtocolServerTrait<CI>, CI> UbiAccountManagementProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: UbiAccountManagementProtocolServerTrait<CI>, CI> Protocol<CI>
    for UbiAccountManagementProtocolServer<T, CI>
{
    fn id(&self) -> u16 {
        UBI_ACCOUNT_MANAGEMENT_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "UbiAccountManagementProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        23u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = UbiAccountManagementProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(UbiAccountManagementProtocolMethod::CreateAccount) => {
                let req = CreateAccountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .create_account(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::UpdateAccount) => {
                let req = UpdateAccountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .update_account(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::GetAccount) => {
                let req = GetAccountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_account(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LinkAccount) => {
                let req = LinkAccountRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .link_account(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::GetTos) => {
                let req = GetTosRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_tos(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::ValidateUsername) => {
                let req = ValidateUsernameRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .validate_username(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::ValidatePassword) => {
                let req = ValidatePasswordRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .validate_password(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::ValidateEmail) => {
                let req = ValidateEmailRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .validate_email(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::GetCountryList) => {
                let req = GetCountryListRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_country_list(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::ForgetPassword) => {
                let req = ForgetPasswordRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .forget_password(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupPrincipalIds) => {
                let req = LookupPrincipalIdsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .lookup_principal_ids(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByPids) => {
                let req = LookupUbiAccountIDsByPidsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_ubi_account_ids_by_pids(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernames) => {
                let req = LookupUbiAccountIDsByUsernamesRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_ubi_account_ids_by_usernames(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUsernamesByUbiAccountIDs) => {
                let req = LookupUsernamesByUbiAccountIDsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_usernames_by_ubi_account_ids(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernameSubString) => {
                let req =
                    LookupUbiAccountIDsByUsernameSubStringRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_ubi_account_ids_by_username_sub_string(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::UserHasPlayed) => {
                let req = UserHasPlayedRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .user_has_played(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::IsUserPlaying) => {
                let req = IsUserPlayingRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .is_user_playing(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernamesGlobal) => {
                let req =
                    LookupUbiAccountIDsByUsernamesGlobalRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_ubi_account_ids_by_usernames_global(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByEmailsGlobal) => {
                let req =
                    LookupUbiAccountIDsByEmailsGlobalRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_ubi_account_ids_by_emails_global(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::LookupUsernamesByUbiAccountIDsGlobal) => {
                let req =
                    LookupUsernamesByUbiAccountIDsGlobalRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.lookup_usernames_by_ubi_account_ids_global(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::GetTosEx) => {
                let req = GetTosExRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .get_tos_ex(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::HasAcceptedLatestTos) => {
                let req = HasAcceptedLatestTosRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .has_accepted_latest_tos(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(UbiAccountManagementProtocolMethod::AcceptLatestTos) => {
                let req = AcceptLatestTosRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .accept_latest_tos(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        UbiAccountManagementProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait UbiAccountManagementProtocolServerTrait<CI> {
    fn create_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: CreateAccountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<CreateAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(create_account)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn update_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UpdateAccountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<UpdateAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(update_account)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetAccountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_account)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn link_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LinkAccountRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LinkAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(link_account)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTosRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_tos)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn validate_username(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidateUsernameRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ValidateUsernameResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_username)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn validate_password(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidatePasswordRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ValidatePasswordResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_password)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn validate_email(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidateEmailRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ValidateEmailResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_email)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_country_list(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetCountryListRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetCountryListResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_country_list)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn forget_password(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ForgetPasswordRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ForgetPasswordResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(forget_password)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_principal_ids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupPrincipalIdsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupPrincipalIdsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_principal_ids)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_ubi_account_ids_by_pids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByPidsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUbiAccountIDsByPidsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_pids)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_ubi_account_ids_by_usernames(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernamesRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUbiAccountIDsByUsernamesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_usernames)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_usernames_by_ubi_account_ids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUsernamesByUbiAccountIDsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUsernamesByUbiAccountIDsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_usernames_by_ubi_account_ids)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_ubi_account_ids_by_username_sub_string(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernameSubStringRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUbiAccountIDsByUsernameSubStringResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_username_sub_string)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn user_has_played(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UserHasPlayedRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<UserHasPlayedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(user_has_played)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn is_user_playing(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: IsUserPlayingRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<IsUserPlayingResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(is_user_playing)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_ubi_account_ids_by_usernames_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernamesGlobalRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUbiAccountIDsByUsernamesGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_usernames_global)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_ubi_account_ids_by_emails_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByEmailsGlobalRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUbiAccountIDsByEmailsGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_emails_global)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn lookup_usernames_by_ubi_account_ids_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUsernamesByUbiAccountIDsGlobalRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<LookupUsernamesByUbiAccountIDsGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_usernames_by_ubi_account_ids_global)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_tos_ex(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTosExRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetTosExResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_tos_ex)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn has_accepted_latest_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: HasAcceptedLatestTosRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<HasAcceptedLatestTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(has_accepted_latest_tos)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn accept_latest_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: AcceptLatestTosRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<AcceptLatestTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(accept_latest_tos)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct UbiAccountManagementProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> UbiAccountManagementProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for UbiAccountManagementProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for UbiAccountManagementProtocolClient<CI> {
    fn id(&self) -> u16 {
        UBI_ACCOUNT_MANAGEMENT_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "UbiAccountManagementProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        23u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        UbiAccountManagementProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> UbiAccountManagementProtocolClient<CI> {
    pub fn create_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: CreateAccountRequest,
    ) -> Result<CreateAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(create_account)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::CreateAccount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn update_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UpdateAccountRequest,
    ) -> Result<UpdateAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(update_account)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::UpdateAccount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetAccountRequest,
    ) -> Result<GetAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_account)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::GetAccount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn link_account(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LinkAccountRequest,
    ) -> Result<LinkAccountResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(link_account)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LinkAccount as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTosRequest,
    ) -> Result<GetTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_tos)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::GetTos as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn validate_username(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidateUsernameRequest,
    ) -> Result<ValidateUsernameResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_username)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::ValidateUsername as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn validate_password(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidatePasswordRequest,
    ) -> Result<ValidatePasswordResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_password)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::ValidatePassword as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn validate_email(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ValidateEmailRequest,
    ) -> Result<ValidateEmailResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(validate_email)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::ValidateEmail as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_country_list(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetCountryListRequest,
    ) -> Result<GetCountryListResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_country_list)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::GetCountryList as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn forget_password(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ForgetPasswordRequest,
    ) -> Result<ForgetPasswordResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(forget_password)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::ForgetPassword as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_principal_ids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupPrincipalIdsRequest,
    ) -> Result<LookupPrincipalIdsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_principal_ids)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupPrincipalIds as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_ubi_account_ids_by_pids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByPidsRequest,
    ) -> Result<LookupUbiAccountIDsByPidsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_pids)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByPids as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_ubi_account_ids_by_usernames(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernamesRequest,
    ) -> Result<LookupUbiAccountIDsByUsernamesResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_usernames)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernames as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_usernames_by_ubi_account_ids(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUsernamesByUbiAccountIDsRequest,
    ) -> Result<LookupUsernamesByUbiAccountIDsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_usernames_by_ubi_account_ids)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUsernamesByUbiAccountIDs as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_ubi_account_ids_by_username_sub_string(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernameSubStringRequest,
    ) -> Result<LookupUbiAccountIDsByUsernameSubStringResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_username_sub_string)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernameSubString as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn user_has_played(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UserHasPlayedRequest,
    ) -> Result<UserHasPlayedResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(user_has_played)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::UserHasPlayed as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn is_user_playing(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: IsUserPlayingRequest,
    ) -> Result<IsUserPlayingResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(is_user_playing)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::IsUserPlaying as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_ubi_account_ids_by_usernames_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByUsernamesGlobalRequest,
    ) -> Result<LookupUbiAccountIDsByUsernamesGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_usernames_global)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByUsernamesGlobal as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_ubi_account_ids_by_emails_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUbiAccountIDsByEmailsGlobalRequest,
    ) -> Result<LookupUbiAccountIDsByEmailsGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_ubi_account_ids_by_emails_global)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUbiAccountIDsByEmailsGlobal as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn lookup_usernames_by_ubi_account_ids_global(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: LookupUsernamesByUbiAccountIDsGlobalRequest,
    ) -> Result<LookupUsernamesByUbiAccountIDsGlobalResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(lookup_usernames_by_ubi_account_ids_global)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::LookupUsernamesByUbiAccountIDsGlobal as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_tos_ex(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTosExRequest,
    ) -> Result<GetTosExResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(get_tos_ex)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::GetTosEx as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn has_accepted_latest_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: HasAcceptedLatestTosRequest,
    ) -> Result<HasAcceptedLatestTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(has_accepted_latest_tos)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::HasAcceptedLatestTos as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn accept_latest_tos(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: AcceptLatestTosRequest,
    ) -> Result<AcceptLatestTosResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "UbiAccountManagementProtocol",
            stringify!(accept_latest_tos)
        );
        self.send(
            logger,
            ctx,
            ci,
            UbiAccountManagementProtocolMethod::AcceptLatestTos as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
