// pub mod account_management_service;
pub mod authentication_foundation;
pub mod challenge_helper_service;
pub mod clan_helper_service;
// pub mod friends_service;
pub mod game_session_ex_service;
pub mod game_session_service;
// pub mod health_service;
pub mod ladder_helper_service;
pub mod localization_service;
pub mod nat_traversal;
// pub mod news_service;
// pub mod offline_game_notifications_service;
pub mod player_stats_service;
pub mod privileges_service;
// pub mod protocol_foundation;
pub mod secure_connection_service;
// pub mod simple_authentication;
pub mod tracking_service;
pub mod trackingextension;
pub mod ubi_account_management_service;
pub mod ubi_authentication;
pub mod uplay_win_service;
// pub mod user_account_management_service;
pub mod user_storage;
// pub mod user_storage_admin;
// pub mod web_notifications_storage_service;
