// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

use super::super::game_session_service::types::GameSessionQuery;
use super::types::*;
pub const GAME_SESSION_EX_PROTOCOL_ID: u16 = 123u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum GameSessionExProtocolMethod {
    SearchSessions = 1u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsRequest {
    pub game_session_query: GameSessionQuery,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SearchSessionsResponse {
    pub search_results: quazal::rmc::types::QList<GameSessionSearchResultEx>,
}
pub struct GameSessionExProtocolServer<T: GameSessionExProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: GameSessionExProtocolServerTrait<CI>, CI> GameSessionExProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: GameSessionExProtocolServerTrait<CI>, CI> Protocol<CI>
    for GameSessionExProtocolServer<T, CI>
{
    fn id(&self) -> u16 {
        GAME_SESSION_EX_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "GameSessionExProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        1u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = GameSessionExProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(GameSessionExProtocolMethod::SearchSessions) => {
                let req = SearchSessionsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .search_sessions(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        GameSessionExProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait GameSessionExProtocolServerTrait<CI> {
    fn search_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSessionsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SearchSessionsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "GameSessionExProtocol",
            stringify!(search_sessions)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct GameSessionExProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> GameSessionExProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> ClientProtocol<CI> for GameSessionExProtocolClient<CI> {
    fn id(&self) -> u16 {
        GAME_SESSION_EX_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "GameSessionExProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        1u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        GameSessionExProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> GameSessionExProtocolClient<CI> {
    pub fn search_sessions(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SearchSessionsRequest,
    ) -> Result<SearchSessionsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "GameSessionExProtocol",
            stringify!(search_sessions)
        );
        self.send(
            logger,
            ctx,
            ci,
            GameSessionExProtocolMethod::SearchSessions as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
