// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const LOCALIZATION_PROTOCOL_ID: u16 = 39u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum LocalizationProtocolMethod {
    GetLocaleCode = 1u32,
    SetLocaleCode = 2u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetLocaleCodeRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct GetLocaleCodeResponse {
    pub local_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetLocaleCodeRequest {
    pub local_code: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct SetLocaleCodeResponse;
pub struct LocalizationProtocolServer<T: LocalizationProtocolServerTrait<CI>, CI>(T, ::std::marker::PhantomData<CI>);
impl<T: LocalizationProtocolServerTrait<CI>, CI> LocalizationProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: LocalizationProtocolServerTrait<CI>, CI> Protocol<CI> for LocalizationProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        LOCALIZATION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "LocalizationProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        2u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = LocalizationProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(LocalizationProtocolMethod::GetLocaleCode) => {
                let req = GetLocaleCodeRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_locale_code(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(LocalizationProtocolMethod::SetLocaleCode) => {
                let req = SetLocaleCodeRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.set_locale_code(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        LocalizationProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait LocalizationProtocolServerTrait<CI> {
    fn get_locale_code(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetLocaleCodeRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetLocaleCodeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "LocalizationProtocol",
            stringify!(get_locale_code)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn set_locale_code(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetLocaleCodeRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<SetLocaleCodeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "LocalizationProtocol",
            stringify!(set_locale_code)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct LocalizationProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> LocalizationProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for LocalizationProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for LocalizationProtocolClient<CI> {
    fn id(&self) -> u16 {
        LOCALIZATION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "LocalizationProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        2u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        LocalizationProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> LocalizationProtocolClient<CI> {
    pub fn get_locale_code(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetLocaleCodeRequest,
    ) -> Result<GetLocaleCodeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "LocalizationProtocol",
            stringify!(get_locale_code)
        );
        self.send(
            logger,
            ctx,
            ci,
            LocalizationProtocolMethod::GetLocaleCode as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn set_locale_code(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: SetLocaleCodeRequest,
    ) -> Result<SetLocaleCodeResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "LocalizationProtocol",
            stringify!(set_locale_code)
        );
        self.send(
            logger,
            ctx,
            ci,
            LocalizationProtocolMethod::SetLocaleCode as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
