// AUTOGENERATED with quazal-tools

#![allow(clippy::enum_variant_names, clippy::upper_case_acronyms)]
use super::super::protocol_foundation::types::NotificationEvent;
#[derive(Debug, ToStream, FromStream)]
pub struct TimedNotification {
    pub data: quazal::rmc::types::Data,
    pub timestamp: quazal::rmc::types::DateTime,
    pub notification: NotificationEvent,
}
