// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

use super::types::*;
pub const WEB_NOTIFICATIONS_STORAGE_PROTOCOL_ID: u16 = todo!();
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum WebNotificationsStorageProtocolMethod {
    RegisterUser = 1u32,
    PollNotifications = 2u32,
    UnregisterUser = 3u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct RegisterUserRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct RegisterUserResponse;
#[derive(Debug, ToStream, FromStream)]
pub struct PollNotificationsRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct PollNotificationsResponse {
    pub list_notifications: String,
    pub nb_notifications: i32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UnregisterUserRequest;
#[derive(Debug, ToStream, FromStream)]
pub struct UnregisterUserResponse;
pub struct WebNotificationsStorageProtocolServer<
    T: WebNotificationsStorageProtocolServerTrait<CI>,
    CI,
>(T, ::std::marker::PhantomData<CI>);
impl<T: WebNotificationsStorageProtocolServerTrait<CI>, CI>
    WebNotificationsStorageProtocolServer<T, CI>
{
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: WebNotificationsStorageProtocolServerTrait<CI>, CI> Protocol<CI>
    for WebNotificationsStorageProtocolServer<T, CI>
{
    fn id(&self) -> u16 {
        WEB_NOTIFICATIONS_STORAGE_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "WebNotificationsStorageProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        3u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = WebNotificationsStorageProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(WebNotificationsStorageProtocolMethod::RegisterUser) => {
                let req = RegisterUserRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .register_user(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(WebNotificationsStorageProtocolMethod::PollNotifications) => {
                let req = PollNotificationsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .poll_notifications(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(WebNotificationsStorageProtocolMethod::UnregisterUser) => {
                let req = UnregisterUserRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self
                    .0
                    .unregister_user(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        WebNotificationsStorageProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait WebNotificationsStorageProtocolServerTrait<CI> {
    fn register_user(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: RegisterUserRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<RegisterUserResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(register_user)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn poll_notifications(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: PollNotificationsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<PollNotificationsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(poll_notifications)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn unregister_user(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UnregisterUserRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<UnregisterUserResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(unregister_user)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct WebNotificationsStorageProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> WebNotificationsStorageProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> ClientProtocol<CI> for WebNotificationsStorageProtocolClient<CI> {
    fn id(&self) -> u16 {
        WEB_NOTIFICATIONS_STORAGE_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "WebNotificationsStorageProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        3u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        WebNotificationsStorageProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> WebNotificationsStorageProtocolClient<CI> {
    pub fn register_user(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: RegisterUserRequest,
    ) -> Result<RegisterUserResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(register_user)
        );
        self.send(
            logger,
            ctx,
            ci,
            WebNotificationsStorageProtocolMethod::RegisterUser as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn poll_notifications(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: PollNotificationsRequest,
    ) -> Result<PollNotificationsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(poll_notifications)
        );
        self.send(
            logger,
            ctx,
            ci,
            WebNotificationsStorageProtocolMethod::PollNotifications as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn unregister_user(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: UnregisterUserRequest,
    ) -> Result<UnregisterUserResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "WebNotificationsStorageProtocol",
            stringify!(unregister_user)
        );
        self.send(
            logger,
            ctx,
            ci,
            WebNotificationsStorageProtocolMethod::UnregisterUser as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
