// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const NOTIFICATION_PROTOCOL_ID: u16 = todo!();
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum NotificationProtocolMethod {
    ProcessNotificationEvent = 1u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ProcessNotificationEventRequest {
    pub o_event: NotificationEvent,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ProcessNotificationEventResponse;
pub struct NotificationProtocolServer<T: NotificationProtocolServerTrait<CI>, CI>(T, ::std::marker::PhantomData<CI>);
impl<T: NotificationProtocolServerTrait<CI>, CI> NotificationProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: NotificationProtocolServerTrait<CI>, CI> Protocol<CI> for NotificationProtocolServer<T, CI> {
    fn id(&self) -> u16 {
        NOTIFICATION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "NotificationProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        1u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = NotificationProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(NotificationProtocolMethod::ProcessNotificationEvent) => {
                let req = ProcessNotificationEventRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.process_notification_event(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        NotificationProtocolMethod::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait NotificationProtocolServerTrait<CI> {
    fn process_notification_event(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ProcessNotificationEventRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<ProcessNotificationEventResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "NotificationProtocol", stringify!(process_notification_event));
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct NotificationProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> NotificationProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for NotificationProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for NotificationProtocolClient<CI> {
    fn id(&self) -> u16 {
        NOTIFICATION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "NotificationProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        1u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        NotificationProtocolMethod::try_from(method_id).ok().map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> NotificationProtocolClient<CI> {
    pub fn process_notification_event(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: ProcessNotificationEventRequest,
    ) -> Result<ProcessNotificationEventResponse, Error> {
        warn!(logger, "Method {}.{} not implemented", "NotificationProtocol", stringify!(process_notification_event));
        self.send(logger, ctx, ci, NotificationProtocolMethod::ProcessNotificationEvent as u32, request.to_bytes());
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
