// AUTOGENERATED with quazal-tools
#![allow(
    clippy::enum_variant_names,
    clippy::module_name_repetitions,
    clippy::too_many_lines,
    clippy::upper_case_acronyms,
    clippy::wildcard_imports
)]
use std::convert::TryFrom;

use num_enum::TryFromPrimitive;
use quazal::prudp::ClientRegistry;
use quazal::rmc::basic::FromStream;
use quazal::rmc::basic::ToStream;
use quazal::rmc::ClientProtocol;
use quazal::rmc::Error;
use quazal::rmc::Protocol;
use quazal::rmc::Request;
use quazal::ClientInfo;
use quazal::Context;
use slog::Logger;

#[allow(unused)]
use super::types::*;
pub const TRACKING_EXTENSION_PROTOCOL_ID: u16 = 1001u16;
#[derive(Debug, TryFromPrimitive)]
#[repr(u32)]
pub enum TrackingExtensionProtocolMethod {
    GetTrackingUserGroup = 1u32,
    GetTrackingUserGroupTags = 2u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTrackingUserGroupRequest {
    pub pid: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTrackingUserGroupResponse {
    pub usergroup: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTrackingUserGroupTagsRequest {
    pub usergroup: u32,
}
#[derive(Debug, ToStream, FromStream)]
pub struct GetTrackingUserGroupTagsResponse {
    pub tags: Vec<String>,
}
pub struct TrackingExtensionProtocolServer<T: TrackingExtensionProtocolServerTrait<CI>, CI>(
    T,
    ::std::marker::PhantomData<CI>,
);
impl<T: TrackingExtensionProtocolServerTrait<CI>, CI> TrackingExtensionProtocolServer<T, CI> {
    pub fn new(implementation: T) -> Self {
        Self(implementation, ::std::marker::PhantomData)
    }
}
impl<T: TrackingExtensionProtocolServerTrait<CI>, CI> Protocol<CI>
    for TrackingExtensionProtocolServer<T, CI>
{
    fn id(&self) -> u16 {
        TRACKING_EXTENSION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "TrackingExtensionProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        2u32
    }
    fn handle(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: &Request,
        client_registry: &ClientRegistry<CI>,
        socket: &std::net::UdpSocket,
    ) -> Result<Vec<u8>, Error> {
        let method = TrackingExtensionProtocolMethod::try_from(request.method_id).ok();
        match method {
            None => Err(Error::UnknownMethod),
            Some(TrackingExtensionProtocolMethod::GetTrackingUserGroup) => {
                let req = GetTrackingUserGroupRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp =
                    self.0
                        .get_tracking_user_group(logger, ctx, ci, req, client_registry, socket);
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
            Some(TrackingExtensionProtocolMethod::GetTrackingUserGroupTags) => {
                let req = GetTrackingUserGroupTagsRequest::from_bytes(&request.parameters)?;
                debug!(logger, "Request: {:?}", req);
                let resp = self.0.get_tracking_user_group_tags(
                    logger,
                    ctx,
                    ci,
                    req,
                    client_registry,
                    socket,
                );
                debug!(logger, "Response: {:?}", resp);
                Ok(resp?.to_bytes())
            }
        }
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        TrackingExtensionProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
pub trait TrackingExtensionProtocolServerTrait<CI> {
    fn get_tracking_user_group(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTrackingUserGroupRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetTrackingUserGroupResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "TrackingExtensionProtocol",
            stringify!(get_tracking_user_group)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    fn get_tracking_user_group_tags(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTrackingUserGroupTagsRequest,
        client_registry: &ClientRegistry<CI>,
        _socket: &std::net::UdpSocket,
    ) -> Result<GetTrackingUserGroupTagsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "TrackingExtensionProtocol",
            stringify!(get_tracking_user_group_tags)
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
pub struct TrackingExtensionProtocolClient<CI>(::std::marker::PhantomData<CI>);
impl<CI> TrackingExtensionProtocolClient<CI> {
    pub fn new() -> Self {
        Self(::std::marker::PhantomData)
    }
}
impl<CI> Default for TrackingExtensionProtocolClient<CI> {
    fn default() -> Self {
        Self::new()
    }
}
impl<CI> ClientProtocol<CI> for TrackingExtensionProtocolClient<CI> {
    fn id(&self) -> u16 {
        TRACKING_EXTENSION_PROTOCOL_ID
    }
    fn name(&self) -> String {
        "TrackingExtensionProtocol".to_string()
    }
    fn num_methods(&self) -> u32 {
        2u32
    }
    fn method_name(&self, method_id: u32) -> Option<String> {
        TrackingExtensionProtocolMethod::try_from(method_id)
            .ok()
            .map(|e| format!("{:?}", e))
    }
}
#[allow(unused_variables)]
impl<CI> TrackingExtensionProtocolClient<CI> {
    pub fn get_tracking_user_group(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTrackingUserGroupRequest,
    ) -> Result<GetTrackingUserGroupResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "TrackingExtensionProtocol",
            stringify!(get_tracking_user_group)
        );
        self.send(
            logger,
            ctx,
            ci,
            TrackingExtensionProtocolMethod::GetTrackingUserGroup as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
    pub fn get_tracking_user_group_tags(
        &self,
        logger: &Logger,
        ctx: &Context,
        ci: &mut ClientInfo<CI>,
        request: GetTrackingUserGroupTagsRequest,
    ) -> Result<GetTrackingUserGroupTagsResponse, Error> {
        warn!(
            logger,
            "Method {}.{} not implemented",
            "TrackingExtensionProtocol",
            stringify!(get_tracking_user_group_tags)
        );
        self.send(
            logger,
            ctx,
            ci,
            TrackingExtensionProtocolMethod::GetTrackingUserGroupTags as u32,
            request.to_bytes(),
        );
        Err(quazal::rmc::Error::UnimplementedMethod)
    }
}
