name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    permissions: 
      contents: read

    env:
      PROTOC: bin/protoc.exe

    steps:
    - uses: actions/checkout@v4
    - name: Download protoc
      id: downloader
      uses: actions/download-artifact@v4
      with:
        repository: protocolbuffers/protobuf
        pattern: "protoc-*-win64.zip"
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unpack protoc
      run: 7z x ${{steps.downloader.outputs.download-path}}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
